{% set version = "5.0.1" %}

package:
  name: zope.interface
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/z/zope.interface/zope.interface-{{ version }}.tar.gz
  sha256: dd0bc4016ec9ffa6d327bf3ba2f044c3ff376880661e5cc38c622e1ae023076f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - zope
    - zope.interface
    - zope.interface.common
    - zope.interface.common.tests
    - zope.interface.common.mapping
    - zope.interface._zope_interface_coptimizations
    - zope.interface.tests

about:
  home: http://docs.zope.org/zope.interface/
  license: ZPL-2.1
  license_family: Other
  license_file: LICENSE.txt
  summary: Interfaces for Python
  description: |
    Provides an implementation of object interfaces for Python.Interfaces are objects
    that specify the external behavior of objects that provide them.
  doc_url: http://docs.zope.org/zope.interface/
  doc_source_url: https://github.com/zopefoundation/zope.interface//blob/master/docs/index.rst
  dev_url: https://github.com/zopefoundation/zope.interface

extra:
  recipe-maintainers:
    - isuruf
    - ocefpaf
