travis:
  secure:
    BINSTAR_TOKEN: ZeE59jxKI7o1bZi3wreCvHPglVOTdiaysY8H34ac/wom2vmfnUZXCpR6x75m8pCxDyF131HGnswppFtk+3q5w8GFhhxuon5Q+v3zIfWbY5SOs9MbnHNybY4084h1qW1fZMIAfJOgdPwGk2JQkX8oAmTZ5E8Zsd3rmF8IID1fvxQ5NdBgyUdx1vOgbSLvYrBsKxv5jpFtMQkTmUjxslvMuAQzKrzyNSz5aqPXUIWPQRv1fQtFEpBEqwHWr5qBsuGEnRSbZQubmm/S6Wx9bbqYEbSZ7qdPxpbtD4yHZDP8M/uoyYio5LWd5agYBFiKOg6aFdQSrpPmMOoEigiIEfhofjSRPU24M4n57AKkaaqJcRErkohhGNVBGNoBUrsvNuyl5pAcuiLGijBdURuNscglTfV9MdBkKwEo4uEls2NxjZjRdwgsOT+ancIQkL1I3qSVhtz4aFHtX+LcZy1AlUZAmz6ujBCOE7JADjSZ2FfaSyEJWXFvFEHrYViLFt2GC6em9o//vm+mO6hnVWTQOREAwZEW6wy61Awa2SELbJWZDQ1wyOULG+Ec1FVAYjyTTVQlOsG4swHePFDPxehag9lEwRE2X+NqMaqPZlecCkdIdVD5OADzYRilOz+cpjl9PP2X1Jr9/zcJ7v5qAwQHU7APGgEmtVrEQQ82odXZEFFUFdY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
